# Generated by Django 5.2.6 on 2025-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
