# Generated by Django 5.2.6 on 2025-10-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='updated_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
