# Generated by Django 5.2.6 on 2025-11-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_performancereview_bonus_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_limit', models.IntegerField(default=12)),
                ('vacation_limit', models.IntegerField(default=12)),
                ('unpaid_limit', models.IntegerField(default=9999)),
            ],
            options={
                'verbose_name': 'Leave Limit',
                'verbose_name_plural': 'Leave Limits',
            },
        ),
    ]
