# Generated by Django 5.2.6 on 2025-10-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
