# Generated by Django 5.2.6 on 2025-11-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_leavelimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavelimit',
            options={},
        ),
        migrations.RemoveField(
            model_name='leavelimit',
            name='unpaid_limit',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_unpaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='type',
            field=models.CharField(choices=[('sick', 'Sick'), ('vacation', 'Vacation')], max_length=20),
        ),
    ]
