# Generated by Django 5.2.6 on 2025-11-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_performancereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='bonus_amount',
        ),
    ]
