# Generated by Django 5.2.6 on 2025-10-27 03:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da', models.FloatField(default=0.0, help_text='Dearness Allowance (%)')),
                ('hra', models.FloatField(default=0.0, help_text='House Rent Allowance (%)')),
                ('pf', models.FloatField(default=0.0, help_text='Provident Fund (%)')),
                ('esi', models.FloatField(default=0.0, help_text='Employees State Insurance (%)')),
                ('effective_from', models.DateField(help_text='Date from which these rates are effective')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Edit Requested', 'Edit Requested')], default='Pending', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GrossSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('da_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hra_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gross_salaries', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employee.employee')),
                ('gross', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.grosssalary')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employee.employee')),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='TotalDeductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('esi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('gross_salary_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_summary', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TaxDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('health_insurance', 'Health Insurance'), ('income_tax', 'Income Tax'), ('retirement_fund', 'Retirement Fund'), ('other', 'Other')], max_length=25)),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicable_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_deductions', to='employee.employee')),
                ('deduction_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_deductions', to='payroll.totaldeductions')),
            ],
        ),
        migrations.AddField(
            model_name='payroll',
            name='deductions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.totaldeductions'),
        ),
    ]
