# Generated by Django 5.2.6 on 2025-11-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdeduction',
            name='tax_type',
        ),
    ]
